version: '2.0'

services:

  database:
    image: neo4j:3.5
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_conf:/conf
      - ./neo4j_plugins:/plugins
    environment:
      - "NEO4J_dbms_active__database=graph.db"
    container_name: db_neo4j
